### ISSUE TITLE
Handle view and form display resource type aliasing

### ISSUE THREAD

**Issue by mglaman** [druxt/druxt-schema#31]
**Describe the bug**
In our platform, we have aliased `entity_${schemaType}_display` to use plurals and drop the redundant `--entity_${schemaType}_display` in the resource type.

We need a way to configure replacements for the schema.

```
      const resourceType = `entity_${schemaType}_display--entity_${schemaType}_display`
```

Our URLs look like

```
/jsonapi/entity-form-displays
/jsonapi/entity-view-displays
```

Our types

```
"type": "entity-form-display"
"type": "entity-view-display"
```

**Comment by mglaman** [comment]
Source: https://github.com/druxt/druxt-schema/blob/develop/src/schema.js#L79

**Comment by mglaman** [comment]
We also need to allow mapping the entity type assumptions to aliases.

```
      for (const display of displays) {
        const resource = index[[display.attributes.targetEntityType, display.attributes.bundle].join('--')]
```

expects: `commerce_product_variation--default`
we have: `product-variations--default`

**Comment by mglaman** [comment]
I think we need a mapping which says

```
commerce_product_variation: 'product-variations'
```

**Comment by Decipher** [comment]
Hi @mglaman,

There is an open issue for this already at https://github.com/druxt/druxt-schema/issues/6

**Comment by Decipher** [comment]
Actually, this issue was moved to the `druxt-router`, which also has available work started: https://github.com/druxt/druxt-router/issues/40

The concept is that the router scans the JSON:API index and builds an index of resources, including the remapped paths.

**Comment by mglaman** [comment]
Closing for the original issue
