### ISSUE TITLE
Add support for remapped resources.

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt-schema#6]
As a user of Contenta I need schema support for remapped resources.

Contenta remaps some of the resources by default, which causes issues with relationships as well as ensuring a valid schema.

The JSON API resource config has all the relevant information to resolve the issue.

**Comment by mglaman** [comment]
There is a chance that the mapping _will not be known_ from JSON:API Extras config. I'm working on adding the aliasing via code into Drupal core: https://www.drupal.org/project/drupal/issues/3105318

**Comment by Decipher** [comment]
Thanks @mglaman,

I'm actually going to close this issue, as the communication with Drupal should live in the https://github.com/druxt/druxt-router, DruxtSchema will just consume the data.
